# Generated by Django 4.2.4 on 2023-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkrapp', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_sexuality',
            field=models.CharField(choices=[('HOM', 'HOMOSEXUAL'), ('HET', 'HETEROSEXUAL'), ('BIS', 'BISEXUAL'), ('PAN', 'PANSEXUAL'), ('ASE', 'ASEXUAL'), ('DEM', 'DEMISEXUAL'), ('QUE', 'QUEER'), ('QUS', 'QUESTIONING'), ('NON', 'Prefer not to say')], default='NON', max_length=3),
        ),
    ]
